---
- name: set yum-cron config template
  when:
  - aspects_yum_cron_enabled
  - ansible_distribution == "CentOS"
  - ansible_distribution_major_version == "7"
  template:
    src: "etc-sysconfig-yum-cron.j2"
    dest: "/etc/sysconfig/yum-cron"
  notify:
    - restart yum-cron
  tags:
    - aspects_yum_cron
